# Generated by Django 4.2.1 on 2023-08-11 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shortuuid.django_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('status', models.CharField(choices=[('Rented', 'Rented'), ('Available', 'Available'), ('Sold', 'Sold')], default=('Available', 'Available'), max_length=100, null=True)),
                ('username', models.CharField(max_length=100, null=True)),
                ('password', models.CharField(max_length=100, null=True)),
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=10)),
                ('phone_number', models.CharField(max_length=10, null=True)),
                ('dob', models.DateField(null=True)),
                ('coins', models.IntegerField(default=0, null=True)),
                ('profile_image', models.ImageField(blank=True, default='default_user_image.jpeg', null=True, upload_to='')),
                ('description', models.TextField(default='A new member of RevustG', max_length=100, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', shortuuid.django_fields.ShortUUIDField(alphabet=None, length=10, max_length=30, prefix='O', primary_key=True, serialize=False, unique=True)),
                ('customer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=100, null=True)),
                ('platform_icon', models.ImageField(blank=True, default='default_product_image.jpg', null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', shortuuid.django_fields.ShortUUIDField(alphabet=None, length=10, max_length=30, prefix='PD', primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('sell_price', models.FloatField(null=True)),
                ('rent_price', models.FloatField(null=True)),
                ('cover_img', models.ImageField(blank=True, default='default_product_image.jpg', null=True, upload_to='')),
                ('avt_img', models.ImageField(blank=True, default='default_product_image.jpg', null=True, upload_to='')),
                ('publisher', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(null=True)),
                ('platForm', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.platform')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PurchasedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=100, null=True)),
                ('time', models.DateField(null=True)),
                ('item_id', shortuuid.django_fields.ShortUUIDField(alphabet=None, length=10, max_length=30, prefix='PUR', unique=True)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.account')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, default='default_product_image.jpg', null=True, upload_to='')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.product')),
            ],
            options={
                'verbose_name_plural': 'Product Image',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='tag',
            field=models.ManyToManyField(to='accounts.tag'),
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_product_id', shortuuid.django_fields.ShortUUIDField(alphabet=None, length=10, max_length=30, prefix='OP', unique=True)),
                ('quantity', models.IntegerField(default=0, null=True)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.product')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.product'),
        ),
    ]
