# Generated by Django 4.2.1 on 2023-07-30 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customer_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='coins',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
