# Generated by Django 4.2.1 on 2023-08-13 14:39

from django.db import migrations
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_favoriteproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet=None, length=10, max_length=30, prefix='A', primary_key=True, serialize=False, unique=True),
        ),
    ]
