# Generated by Django 4.2.1 on 2023-08-13 16:25

from django.db import migrations
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_account_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='id',
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='order_product_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet=None, length=10, max_length=30, prefix='OP', primary_key=True, serialize=False, unique=True),
        ),
    ]
