# Generated by Django 4.2.1 on 2023-07-30 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customer_coins'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='profile_image',
            field=models.ImageField(blank=True, default='default_user_image.jpeg', null=True, upload_to=''),
        ),
    ]
