# Generated by Django 4.2.1 on 2023-08-13 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_orderproduct_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderproduct',
            old_name='order_product_id',
            new_name='id',
        ),
    ]
