# Generated by Django 4.2.1 on 2023-08-01 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customer_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseditem',
            name='item_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
