# Generated by Django 4.2.1 on 2023-08-14 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_order_product_id_orderproduct_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='type',
            field=models.CharField(choices=[('Rent', 'Rent'), ('Buy', 'Buy')], default=('Buy', 'Buy'), max_length=30, null=True),
        ),
    ]
