# Generated by Django 4.2.1 on 2023-08-18 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_phonecardpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonecardpayment',
            name='value',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
