# Generated by Django 4.2.1 on 2023-08-18 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_phonecardpayment_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonecardpayment',
            name='value',
            field=models.PositiveIntegerField(choices=[(10000, 10000), (20.0, 20000), (50000, 50000), (100000, 100000), (200000, 200000), (500000, 500000)], default=0),
        ),
    ]
