# Generated by Django 4.2.1 on 2023-09-04 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_bankaccountpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='rent_price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sell_price',
            field=models.IntegerField(null=True),
        ),
    ]
